
services:
  web-app:
    build:
      context: ./web-app
    ports:
      - "5001:5001"
    volumes:
      - ./web-app:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PYTHONUNBUFFERED=1
  ml-recommender:
    build:
      context: ./ml-recommender
    ports:
      - "8000:8000"
    volumes:
      - ./ml-recommender:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo
    command: ["--noauth"] # for dev
    ports:
      - "27017:27017"

